/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FollowsRouteImport } from './routes/follows'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as PlaysPlayIdRouteImport } from './routes/plays.$playId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowsRoute = FollowsRouteImport.update({
  id: '/follows',
  path: '/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaysPlayIdRoute = PlaysPlayIdRouteImport.update({
  id: '/plays/$playId',
  path: '/plays/$playId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/follows': typeof FollowsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/plays/$playId': typeof PlaysPlayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/follows': typeof FollowsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/plays/$playId': typeof PlaysPlayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/follows': typeof FollowsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/plays/$playId': typeof PlaysPlayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/follows' | '/games/$gameId' | '/plays/$playId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/follows' | '/games/$gameId' | '/plays/$playId'
  id: '__root__' | '/' | '/follows' | '/games/$gameId' | '/plays/$playId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FollowsRoute: typeof FollowsRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  PlaysPlayIdRoute: typeof PlaysPlayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follows': {
      id: '/follows'
      path: '/follows'
      fullPath: '/follows'
      preLoaderRoute: typeof FollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$playId': {
      id: '/plays/$playId'
      path: '/plays/$playId'
      fullPath: '/plays/$playId'
      preLoaderRoute: typeof PlaysPlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FollowsRoute: FollowsRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  PlaysPlayIdRoute: PlaysPlayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
