/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as FantasyRouteImport } from './routes/fantasy'
import { Route as FollowsRouteImport } from './routes/follows'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as ReactionsRouteImport } from './routes/reactions'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as PlaysPlayIdRouteImport } from './routes/plays.$playId'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyRoute = FantasyRouteImport.update({
  id: '/fantasy',
  path: '/fantasy',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowsRoute = FollowsRouteImport.update({
  id: '/follows',
  path: '/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactionsRoute = ReactionsRouteImport.update({
  id: '/reactions',
  path: '/reactions',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaysPlayIdRoute = PlaysPlayIdRouteImport.update({
  id: '/plays/$playId',
  path: '/plays/$playId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/fantasy': typeof FantasyRoute
  '/follows': typeof FollowsRoute
  '/predictions': typeof PredictionsRoute
  '/reactions': typeof ReactionsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/plays/$playId': typeof PlaysPlayIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/fantasy': typeof FantasyRoute
  '/follows': typeof FollowsRoute
  '/predictions': typeof PredictionsRoute
  '/reactions': typeof ReactionsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/plays/$playId': typeof PlaysPlayIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/fantasy': typeof FantasyRoute
  '/follows': typeof FollowsRoute
  '/predictions': typeof PredictionsRoute
  '/reactions': typeof ReactionsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/plays/$playId': typeof PlaysPlayIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/fantasy'
    | '/follows'
    | '/predictions'
    | '/reactions'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/plays/$playId'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/fantasy'
    | '/follows'
    | '/predictions'
    | '/reactions'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/plays/$playId'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/fantasy'
    | '/follows'
    | '/predictions'
    | '/reactions'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/plays/$playId'
    | '/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  AlertsRoute: typeof AlertsRoute
  FantasyRoute: typeof FantasyRoute
  FollowsRoute: typeof FollowsRoute
  PredictionsRoute: typeof PredictionsRoute
  ReactionsRoute: typeof ReactionsRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  PlaysPlayIdRoute: typeof PlaysPlayIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy': {
      id: '/fantasy'
      path: '/fantasy'
      fullPath: '/fantasy'
      preLoaderRoute: typeof FantasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follows': {
      id: '/follows'
      path: '/follows'
      fullPath: '/follows'
      preLoaderRoute: typeof FollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reactions': {
      id: '/reactions'
      path: '/reactions'
      fullPath: '/reactions'
      preLoaderRoute: typeof ReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$playId': {
      id: '/plays/$playId'
      path: '/plays/$playId'
      fullPath: '/plays/$playId'
      preLoaderRoute: typeof PlaysPlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  AlertsRoute: AlertsRoute,
  FantasyRoute: FantasyRoute,
  FollowsRoute: FollowsRoute,
  PredictionsRoute: PredictionsRoute,
  ReactionsRoute: ReactionsRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  PlaysPlayIdRoute: PlaysPlayIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
